In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset = pd.read_csv('Data/kc_house_data.csv')
x= dataset.iloc[:,1:-1] #slicing, iloc used for rows
y=dataset.iloc[:,-1].values

In [ ]:
#removing date col
x=x.drop(columns=['date'])

# Importing all Regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,precision_score, recall_score, f1_score,r2_score

In [5]:
dataset

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,7129300520,20141013T000000,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,221900.0
1,6414100192,20141209T000000,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,538000.0
2,5631500400,20150225T000000,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,180000.0
3,2487200875,20141209T000000,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000.0
4,1954400510,20150218T000000,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,510000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,3,2.50,1530,1131,3.0,0,0,3,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,360000.0
21609,6600060120,20150223T000000,4,2.50,2310,5813,2.0,0,0,3,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,400000.0
21610,1523300141,20140623T000000,2,0.75,1020,1350,2.0,0,0,3,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,402101.0
21611,291310100,20150116T000000,3,2.50,1600,2388,2.0,0,0,3,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,400000.0
21612,1523300157,20141015T000000,2,0.75,1020,1076,2.0,0,0,3,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,325000.0

In [6]:
dataset.head(10)

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,7129300520,20141013T000000,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,221900.0
1,6414100192,20141209T000000,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,538000.0
2,5631500400,20150225T000000,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,180000.0
3,2487200875,20141209T000000,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000.0
4,1954400510,20150218T000000,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,510000.0
5,7237550310,20140512T000000,4,4.50,5420,101930,1.0,0,0,3,...,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930,1230000.0
6,1321400060,20140627T000000,3,2.25,1715,6819,2.0,0,0,3,...,1715,0,1995,0,98003,47.3097,-122.327,2238,6819,257500.0
7,2008000270,20150115T000000,3,1.50,1060,9711,1.0,0,0,3,...,1060,0,1963,0,98198,47.4095,-122.315,1650,9711,291850.0
8,2414600126,20150415T000000,3,1.00,1780,7470,1.0,0,0,3,...,1050,730,1960,0,98146,47.5123,-122.337,1780,8113,229500.0
9,3793500160,20150312T000000,3,2.50,1890,6560,2.0,0,0,3,...,1890,0,2003,0,98038,47.3684,-122.031,2390,7570,323000.0

In [7]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   bedrooms       21613 non-null  int64
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64
 5   sqft_lot       21613 non-null  int64
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64
 8   view           21613 non-null  int64
 9   condition      21613 non-null  int64
 10  grade          21613 non-null  int64
 11  sqft_above     21613 non-null  int64
 12  sqft_basement  21613 non-null  int64
 13  yr_built       21613 non-null  int64
 14  yr_renovated   21613 non-null  int64
 15  zipcode        21613 non-null  int64
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 18  sqft_living15  21613 non-null  int64
 19  sqft_lot15     21613 non-null  int64
 20  price          21613 non-null  float64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [ ]:
#It displays the statistical summary of all numeric columns in the dataset.
dataset.describe()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,2.161300e+04
mean,4.580302e+09,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652,5.401822e+05
std,2.876566e+09,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631,3.673622e+05
min,1.000102e+06,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,7.500000e+04
25%,2.123049e+09,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000,3.219500e+05
50%,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000,4.500000e+05
75%,7.308900e+09,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,6.450000e+05
max,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,7.700000e+06

In [9]:
dataset.isna().sum()

id               0
date             0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
price            0
dtype: int64

In [ ]:
print(dataset['price'].value_counts()) # in place of target in this we have price col

price
450000.0     172
350000.0     172
550000.0     159
500000.0     152
425000.0     150
            ...
3570000.0      1
594866.0       1
541800.0       1
610685.0       1
402101.0       1
Name: count, Length: 3625, dtype: int64

In [11]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y,
    test_size=0.25,
    random_state=42
)

In [ ]:
print(x_train.shape) #It displays the shape (dimensions) of the training feature dataset. Op is in form of rows and col  Rows: no of training sample, col- no of ip feature

(16209, 18)

In [ ]:
print(x_test.shape) #print how much rows train

(5404, 18)

In [15]:
scaler = StandardScaler()

In [16]:
x_train = scaler.fit_transform(x_train)

In [17]:
x_test = scaler.transform(x_test)

## Linear Regression

In [18]:
model=LinearRegression()

In [19]:
model

LinearRegression()

In [20]:
model.fit(x_train,y_train)

LinearRegression()

In [21]:
y_pred=model.predict(x_test)

In [22]:
r2=r2_score(y_test,y_pred)# Accurate result

In [23]:
r2

0.704844411407797

## Logistic Regression

In [24]:
model=LogisticRegression()

In [27]:
model

LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

c:\Users\Shikhar Srivastava\OneDrive\Desktop\AI_VIrtual_Internship\Pbel\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [28]:
Lr_pred= model.predict(x_test)

In [29]:
r2=r2_score(y_test,Lr_pred)

In [30]:
r2

0.5893003154232141

### Polynomial Regression

In [31]:
poly= PolynomialFeatures(degree=2)

In [32]:
x_train_poly= poly.fit_transform(x_train)
x_test_poly= poly.transform(x_test)

In [33]:
poly_model= LinearRegression()

In [34]:
poly_model

LinearRegression()

In [35]:
poly_model.fit(x_train_poly,y_train)

LinearRegression()

In [36]:
poly_pred= poly_model.predict(x_test_poly)

In [37]:
poly_r2= r2_score(y_test,poly_pred)

In [38]:
poly_r2

0.8072537772804494

### SVM

In [39]:
svr_model= SVR(kernel='rbf')

In [40]:
svr_model

SVR()

In [41]:
svr_model.fit(x_train,y_train)

SVR()

In [42]:
svr_pred= svr_model.predict(x_test)

In [43]:
svr_r2= r2_score(y_test,svr_pred)

In [44]:
svr_r2

-0.06177529190571818

#### Decision Tree

In [45]:
regressor= DecisionTreeRegressor(random_state=42)

In [46]:
regressor

DecisionTreeRegressor(random_state=42)

In [47]:
regressor.fit(x_train,y_train)

DecisionTreeRegressor(random_state=42)

In [48]:
reg_pred= regressor.predict(x_test)

In [49]:
reg_r2= r2_score(y_test,reg_pred)

In [50]:
reg_r2

0.7311395928307366

#### RandomForestRegression

In [51]:
rf_model= RandomForestRegressor(n_estimators=10,random_state=42)

In [53]:
rf_model

RandomForestRegressor(n_estimators=10, random_state=42)

In [54]:
rf_model.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=42)

In [55]:
rf_pred=rf_model.predict(x_test)

In [56]:
rf_r2= r2_score(y_test,rf_pred)

In [57]:
rf_r2

0.8591490481338582